substitutions:
    devicename: meteo_serra
    data_intro: Serra

esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
wifi:
  ssid: !secret SSID
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename} Fallback Hotspot
    password: !secret wifi_password 

captive_portal:

# Enable logging
logger:
   baud_rate: 0
    # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
uart:
  rx_pin: RX 
  tx_pin: TX 
  baud_rate: 9600
i2c:
  sda: 14
  scl: 15
  frequency: 100khz
  scan: True
  id: bus_a

sensor:
  - platform: sds011
    pm_2_5:
      name: ${data_intro} PM 2.5µm
    pm_10_0:
      name: ${data_intro} PM 10.0µm
    update_interval: 10min 
  - platform: dht
    pin: 22
    temperature:
      name: ${data_intro} Temperature
    humidity:
      name: ${data_intro} Humidity
    model: DHT22
    update_interval: 1min
  - platform: ccs811
    i2c_id: bus_a
    eco2:
      name: ${data_intro} eCO2
      filters:
          - median:
              window_size: 7
              send_every: 4
              send_first_at: 3
    tvoc:
      name: ${data_intro} Total Volatile Organic Compound
      filters:
          - median:
              window_size: 7
              send_every: 4
              send_first_at: 3
    address: 0x5A
    baseline: 0x0464
    update_interval: 1min
  - platform: wifi_signal
    name: ${data_intro} WiFi Signal Sensor
    update_interval: 10min



switch:
  - platform: restart
    name: ${data_intro} ESP32 Restart
#we don't have enough ground pins on the board, we generate one like this.
  - platform: gpio
    internal: true
    pin: 19
    name: "DHT ground"
    restore_mode: ALWAYS_OFF


# Enable Home Assistant API
api:
     password: !secret api_password

ota:
     safe_mode: True
     password: !secret ota_password

web_server:
  port: 80

